ProjectStore/Models/Certification.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectStore.Models
{
    public class Certification
    {
        public int CertificationId { get; set; }

        [Required]
        public string CertificationName { get; set; }

        [Required]
        public string Description { get; set; }

        public int CategorieId { get; set; }

        public Categorie Categorie { get; set; }
    }
}

ProjectStore/Controllers/CertificationController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProjectStore.Models;
using ProjectStore.Models.Repositories;
using ProjectStore.ViewModel;
using System;
using System.IO;

namespace ProjectStore.Controllers
{
    public class CertificationController : Controller
    {
        readonly ICertificationRepository certificationRepository;
        readonly ICategorieRepository categorieRepository;
        private readonly IWebHostEnvironment hostingEnvironment;

        public CertificationController(ICertificationRepository certificationRepository, ICategorieRepository categorieRepository, IWebHostEnvironment hostingEnvironment)
        {
            this.certificationRepository = certificationRepository;
            this.categorieRepository = categorieRepository;
            this.hostingEnvironment = hostingEnvironment;
        }

        // GET: CertificationController
        public ActionResult Index()
        {
            ViewBag.CategorieID = new SelectList(categorieRepository.GetAll(), "CategorielID", "CategorieName");
            return View(certificationRepository.GetAll());
        }

        // GET: CertificationController/Details/5
        public ActionResult Details(int id)
        {
            ViewBag.CategorieID = new SelectList(categorieRepository.GetAll(), "CategorieId", "CategorieName");
            var certification = certificationRepository.GetById(id);
            return View(certification);
        }

        // GET: CertificationController/Create
        public ActionResult Create()
        {
            ViewBag.CategorieID = new SelectList(categorieRepository.GetAll(), "CategorieId", "CategorieName");
            return View();
        }

        // POST: CertificationController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateViewModel model)
        {
            ViewBag.CategorieID = new SelectList(categorieRepository.GetAll(), "CategorieId", "CategorieName");
            if (ModelState.IsValid)
            {
                string uniqueFileName = null;

                // If the Photo property on the incoming model object is not null, then the user
                // has selected an image to upload.
                if (model.Photo != null)
                {
                    // The image must be uploaded to the images folder in wwwroot
                    // To get the path of the wwwroot folder we are using the inject
                    // HostingEnvironment service provided by ASP.NET Core

                    string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");

                    // To make sure the file name is unique we are appending a new
                    // GUID value and an underscore to the file name

                    uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Photo.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                    // Use CopyTo() method provided by IFormFile interface to
                    // copy the file to wwwroot/images folder

                    model.Photo.CopyTo(new FileStream(filePath, FileMode.Create));
                }

                Certification newCertification = new Certification
                {
                    CertificationName = model.CertificationName,
                    Description = model.Description,
                    Price = model.Price,
                    CategorieId = model.CategorieId,
                    Categorie = model.Categorie,
                    // Store the file name in PhotoPath property of the certification object
                    // which gets saved to the Certifications database table
                    PhotoPath = uniqueFileName
                };

                certificationRepository.Add(newCertification);
                return RedirectToAction("details", new { id = newCertification.CertificationId });
            }

            return View();
        }

        // GET: CertificationController/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.CategorieID = new SelectList(categorieRepository.GetAll(), "CategorieId", "CategorieName");
            Certification certification = certificationRepository.GetById(id);
            EditViewModel editViewModel = new EditViewModel
            {
                CertificationId = certification.CertificationId,
                CertificationName = certification.CertificationName,
                Description = certification.Description,
                Price = certification.Price,
                CategorieId = certification.CategorieId,
                Categorie = certification.Categorie,
                ExistingPhotoPath = certification.PhotoPath
            };
            return View(editViewModel);
        }

        // POST: CertificationController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditViewModel model)
        {
            
            // Check if the provided data is valid, if not rerender the edit view
            // so the user can correct and resubmit the edit form
            if (ModelState.IsValid)
            {
                // Retrieve the certification being edited from the database
                Certification certification = certificationRepository.GetById(model.CertificationId);
                // Update the certification object with the data in the model object
                certification.CertificationName = model.CertificationName;
                certification.Description = model.Description;
                certification.Price = model.Price;
                certification.CategorieId = model.CategorieId;
                certification.Categorie = model.Categorie;

                // If the user wants to change the photo, a new photo will be
                // uploaded and the Photo property on the model object receives
                // the uploaded photo. If the Photo property is null, user did
                // not upload a new photo and keeps his existing photo
                if (model.Photo != null)
                {
                    // If a new photo is uploaded, the existing photo must be
                    // deleted. So check if there is an existing photo and delete
                    if (model.ExistingPhotoPath != null)
                    {
                        string filePath = Path.Combine(hostingEnvironment.WebRootPath,
                            "images", model.ExistingPhotoPath);
                        System.IO.File.Delete(filePath);
                    }
                    // Save the new photo in wwwroot/images folder and update
                    // PhotoPath property of the certification object which will be
                    // eventually saved in the database
                    certification.PhotoPath = ProcessUploadedFile(model);
                }

                // Call update method on the repository service passing it the
                // certification object to update the data in the database table
                Certification updatedCertification = certificationRepository.Edit(certification);
                if (updatedCertification != null)
                    return RedirectToAction("index");
                else
                    return NotFound();
            }

            return View(model);
        }

        [NonAction]
        private string ProcessUploadedFile(EditViewModel model)
        {
            string uniqueFileName = null;

            if (model.Photo != null)
            {
                string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Photo.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.Photo.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }

        // GET: CertificationController/Delete/5
        public ActionResult Delete(int id)
        {
            return View(certificationRepository.GetById(id));
        }

        // POST: CertificationController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Certification c)
        {
            try
            {
                certificationRepository.Delete(c);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ProjectStore/Views/Certification/Create.cshtml
@model ProjectStore.ViewModel.CreateViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Certification</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CertificationName" class="control-label"></label>
                <input asp-for="CertificationName" class="form-control" />
                <span asp-validation-for="CertificationName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            @* asp-for tag helper is set to "Photo" property. "Photo" property
                type is IFormFile so at runtime asp.net core generates file upload
                control (input type=file) *@
            <div class="form-group row">
                <label asp-for="Photo" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-10">
                    <div class="custom-file">
                        <input asp-for="Photo" class="form-control custom-file-input">
                        <label class="custom-file-label">Choose File...</label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="CategorieId" class="control-label"></label>
                <select asp-for="CategorieId" class="form-control" asp-items="ViewBag.CategorieId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@

@*This script is required to display the selected file in the file upload element*@

@section Scripts {
    <script>
            $(document).ready(function () {
                $('.custom-file-input').on("change", function () {
                    var fileName = $(this).val().split("\\").pop();
                    $(this).next('.custom-file-label').html(fileName);
                });
            });
    </script>
}

ProjectStore/Views/Certification/Delete.cshtml
@model ProjectStore.Models.Certification

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Certification</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CertificationName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CertificationName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhotoPath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhotoPath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Categorie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Categorie.CategorieId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CertificationId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ProjectStore/Views/Certification/Details.cshtml
@model ProjectStore.Models.Certification
@{
    ViewData["Title"] = "Details";
    var photoPath = "~/images/" + (Model.PhotoPath ?? "noimage.jpg");
}

<h1>Details</h1>

<div>
    <h4>Certification</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CertificationName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CertificationName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Categorie)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Categorie.CategorieName)
        </dd>
        <dt class="col-sm-2">
            <label><b>Photo</b> </label>
        </dt>
        <dd class="col-sm-10">
            <div class="card-body text-left">
                <img src="@photoPath" asp-append-version="true" height="100" width="100" />
            </div>
        </dd>
    </dl>
</div>



<div>
    <a asp-action="Edit" asp-route-id="@Model.CertificationId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ProjectStore/Views/Certification/Edit.cshtml
@model ProjectStore.ViewModel.EditViewModel

@{
    ViewBag.Title = "Edit Certification";
    // Get the full path of the existing certification photo for display
    var photoPath = "~/images/" + (Model.ExistingPhotoPath ?? "noimage.jpg");
}

<form asp-controller="Certification" asp-action="edit" enctype="multipart/form-data" method="post" class="mt-3">
    <div asp-validation-summary="All" class="text-danger">
    </div>
    @*Use hidden input elements to store certification id and ExistingPhotoPath
        which we need when we submit the form and update data in the database*@
    <input hidden asp-for="CertificationId" />
    <input hidden asp-for="ExistingPhotoPath" />

    @*Bind to the properties of the CertificationEditViewModel. The asp-for tag helper
        takes care of displaying the existing data in the respective input elements*@
    <div class="form-group row">
        <label asp-for="CertificationName" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="CertificationName" class="form-control" placeholder="CertificationName">
            <span asp-validation-for="CertificationName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Description" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Description" class="form-control" placeholder="Description">
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="Price" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Price" class="form-control" placeholder="Price">
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="CategorieId" class="control-label"></label>
        <select asp-for="CategorieId" class="form-control" asp-items="ViewBag.CategorieId"></select>
        <span asp-validation-for="CategorieId" class="text-danger"></span>
    </div>
    <div class="form-group row">
        <label asp-for="Photo" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <div class="custom-file">
                <input asp-for="Photo" class="custom-file-input form-control">
                <label class="custom-file-label">cliquer ici pour changer la photo</label>
            </div>
        </div>
    </div>

    @*Display the existing certification photo*@
    <div class="form-group row col-sm-4 offset-4">
        <img src="@photoPath" asp-append-version="true" height="100" width="100" />
    </div>

    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Update</button>
            <a asp-action="index" asp-controller="Certification" class="btn btn-primary">Cancel</a>
        </div>
    </div>
</form>
    @*@section Scripts {
            @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
        }*@


    @section Scripts {
        <script>
            $(document).ready(function () {
                $('.custom-file-input').on("change", function () {
                    var fileName = $(this).val().split("\\").pop();
                    $(this).next('.custom-file-label').html(fileName);
                });
            });
        </script>
    }

ProjectStore/Views/Certification/Index.cshtml
@model IEnumerable<ProjectStore.Models.Certification>

@{
    ViewData["Title"] = "Certificat List";
}

<h1>Certificat List</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<div class="card-deck">
    @foreach (var certification in Model)
    {
        var photoPath = "~/images/" + (certification.PhotoPath ?? "noimage.jpg");
        <div class="card m-3" style="min-width: 18rem; max-width:30.5%;">
            <div class="card-header">
                <h5><b>Name : </b> @certification.CertificationName</h5>
                <h5><b>Description :</b>@certification.Description</h5>
                <h5><b>Price :</b> @certification.Price</h5>
                <h5><b>Categorie :</b> @certification.Categorie.CategorieName</h5>
            </div>

            <img class="card-img-top imageThumbnail" src="@photoPath"
                 asp-append-version="true" />

            <div class="card-footer text-center">
                <a asp-controller="Certification" asp-action="Details" asp-route-id="@certification.CertificationId"
                   class="btn btn-primary m-1">View</a>
                <a asp-action="Edit" asp-controller="Certification" class="btn btn-primary m-1" asp-route-id="@certification.CertificationId">Edit</a>
                <a asp-action="Delete" asp-controller="Certification" class="btn btn-danger m-1" asp-route-id="@certification.CertificationId">Delete</a>
            </div>
        </div>
    }
</div>